# Generated by Django 6.0.1 on 2026-01-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeRecognizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeAnalysis',
            new_name='CodeFiles',
        ),
    ]
