# Generated by Django 6.0.1 on 2026-01-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='spectrum_audio/')),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='spectrum_graphs/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('result_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
