# Generated by Django 6.0.1 on 2026-01-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectrumRecognizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='spectrum_audio/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('result_text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SpectrumAnalysis',
        ),
    ]
